Repository CAUSOLDOUTMEN/Diareat_backend, pull requests merged in 2023-11, with the labels that each got.

#46 Feat: RedisCache를 통한 캐싱 적용 (#44) [잔여 부분]
  src/main/java/com/diareat/diareat/food/controller/FoodController.java
  src/main/java/com/diareat/diareat/food/dto/CreateFoodDto.java
  src/main/java/com/diareat/diareat/food/dto/UpdateFavoriteFoodDto.java
  src/main/java/com/diareat/diareat/food/dto/UpdateFoodDto.java
  src/main/java/com/diareat/diareat/food/repository/FavoriteFoodRepository.java
  src/main/java/com/diareat/diareat/food/repository/FoodRepository.java
  src/main/java/com/diareat/diareat/food/service/FoodService.java
  src/main/java/com/diareat/diareat/util/api/ResponseCode.java
  src/test/java/com/diareat/diareat/service/FoodServiceTest.java
Labels: feat

#53 Feat: FoodService 분석 및 FoodControllerTest 구현 (#50)
  src/main/java/com/diareat/diareat/food/controller/FoodController.java
  src/main/java/com/diareat/diareat/food/domain/Food.java
  src/main/java/com/diareat/diareat/food/dto/ResponseFoodRankDto.java
  src/main/java/com/diareat/diareat/food/repository/FoodRepository.java
  src/main/java/com/diareat/diareat/food/service/FoodService.java
  src/main/java/com/diareat/diareat/util/api/ResponseCode.java
  src/test/java/com/diareat/diareat/controller/FoodControllerTest.java
  src/test/java/com/diareat/diareat/service/FoodServiceTest.java
Labels: feat

#52 Fix: 카카오로그인 에러 수정 (#51)
  src/main/java/com/diareat/diareat/auth/dto/KakaoAccount.java
  src/main/java/com/diareat/diareat/auth/dto/KakaoProfile.java
  src/main/java/com/diareat/diareat/auth/dto/KakaoProperties.java
  src/main/java/com/diareat/diareat/auth/dto/KakaoUserInfoResponse.java
  src/main/java/com/diareat/diareat/auth/service/KakaoAuthService.java
Labels: fix

#55 Feat: 헬스 체크 활성화
  build.gradle
  k8s/manifest.yaml
  src/main/java/com/diareat/diareat/config/WebSecurityConfig.java
  src/main/resources/application.properties
Labels: feat

#61 Fix: 누락된 기준 영양소 수정 (#60)
  k8s/manifest.yaml
  src/main/java/com/diareat/diareat/food/dto/ResponseNutritionSumByDateDto.java
  src/main/java/com/diareat/diareat/food/service/FoodService.java
  src/test/java/com/diareat/diareat/controller/FoodControllerTest.java
Labels: fix

#63 Fix: Cache에서 key값 타입 수정
  src/main/java/com/diareat/diareat/food/service/FoodService.java
  src/test/java/com/diareat/diareat/controller/FoodControllerTest.java
Labels: fix

#65 hotfix: cache 형변환 수정 (#64)
  src/main/java/com/diareat/diareat/food/service/FoodService.java
Labels: fix

#67 Fix: 오늘의영양 응답데이터 LocalDate 주석처리 (#66)
  src/main/java/com/diareat/diareat/food/dto/ResponseNutritionSumByDateDto.java
  src/main/java/com/diareat/diareat/food/service/FoodService.java
  src/test/java/com/diareat/diareat/controller/FoodControllerTest.java
Labels: fix

#68 :ambulance: Fix: Redis 포트번호 미정 문제 수정 (#66)
  src/main/java/com/diareat/diareat/config/RedisCacheConfig.java
  src/main/resources/application.properties
Labels: fix

#71 Fix: ResponseFoodDto Date/Time 타입 주석처리 (#66)
  src/main/java/com/diareat/diareat/food/dto/ResponseFoodDto.java
  src/test/java/com/diareat/diareat/controller/FoodControllerTest.java
Labels: fix

#73 Fix: createFoodDto 날짜 형식 수정 (#72)
  src/main/java/com/diareat/diareat/food/domain/FavoriteFood.java
  src/main/java/com/diareat/diareat/food/domain/Food.java
  src/main/java/com/diareat/diareat/food/dto/CreateFoodDto.java
  src/main/java/com/diareat/diareat/food/dto/ResponseFoodDto.java
  src/main/java/com/diareat/diareat/food/repository/FoodRepository.java
  src/main/java/com/diareat/diareat/food/service/FoodService.java
  src/test/java/com/diareat/diareat/controller/FoodControllerTest.java
  src/test/java/com/diareat/diareat/service/FoodServiceTest.java
Labels: fix

#75 Fix: 테이블의 칼럼 명과 직접 매핑
  src/main/java/com/diareat/diareat/food/domain/Food.java
  src/main/java/com/diareat/diareat/food/service/FoodService.java
  src/test/java/com/diareat/diareat/service/FoodServiceTest.java
Labels: fix

#77 hotfix: sort by 인자 수정 (#76)
  src/main/java/com/diareat/diareat/food/service/FoodService.java
  src/test/java/com/diareat/diareat/service/FoodServiceTest.java
Labels: fix

#79 hotfix: key값의 date string으로 변환 (#78)
  src/main/java/com/diareat/diareat/food/service/FoodService.java
Labels: fix

#81 hotfix: noargsconstructor 추가 (#80)
  src/main/java/com/diareat/diareat/food/dto/ResponseFoodDto.java
Labels: fix

#83 hotfix: responsefooddto의 필드명 변경 (#82)
  src/main/java/com/diareat/diareat/food/dto/ResponseFoodDto.java
Labels: fix

#85 Fix: Redis 캐시 일관성 손실 문제 해결 (#84)
  src/main/java/com/diareat/diareat/food/controller/FoodController.java
  src/main/java/com/diareat/diareat/food/dto/ResponseAnalysisDto.java
  src/main/java/com/diareat/diareat/food/dto/ResponseFavoriteFoodDto.java
  src/main/java/com/diareat/diareat/food/dto/ResponseFoodRankDto.java
  src/main/java/com/diareat/diareat/food/dto/ResponseScoreBestWorstDto.java
  src/main/java/com/diareat/diareat/food/dto/ResponseSimpleFoodDto.java
  src/main/java/com/diareat/diareat/food/service/FoodService.java
  src/main/java/com/diareat/diareat/user/dto/response/ResponseSimpleUserDto.java
  src/main/java/com/diareat/diareat/user/service/UserService.java
  src/main/java/com/diareat/diareat/util/MessageUtil.java
  src/test/java/com/diareat/diareat/controller/FoodControllerTest.java
  src/test/java/com/diareat/diareat/controller/UserControllerTest.java
  src/test/java/com/diareat/diareat/service/FoodServiceTest.java
Labels: fix

#87 Fix: Food와 FavoriteFood 연결 수정
  src/main/java/com/diareat/diareat/food/domain/FavoriteFood.java
  src/main/java/com/diareat/diareat/food/service/FoodService.java
  src/test/java/com/diareat/diareat/controller/FoodControllerTest.java
  src/test/java/com/diareat/diareat/service/FoodServiceTest.java
Labels: fix

#89 fix: food와 favoritefood간 연동 (#88)
  src/main/java/com/diareat/diareat/food/domain/FavoriteFood.java
  src/main/java/com/diareat/diareat/food/domain/Food.java
Labels: fix

#91 chore: cache 없애보기 (#90)
  src/main/java/com/diareat/diareat/food/service/FoodService.java
Labels: fix

#93 Fix: 캐싱 value 일부 수정 (#92)
  src/main/java/com/diareat/diareat/food/service/FoodService.java
Labels: fix

#95 :ambulance: Fix: 오늘의영양 key 공백 끼어있는 상황 수정 (#94)
  src/main/java/com/diareat/diareat/food/service/FoodService.java
Labels: fix

#97 Feat: 즐찾 음식으로부터 음식 생성 메소드 구현 (#96)
  src/main/java/com/diareat/diareat/food/controller/FoodController.java
  src/main/java/com/diareat/diareat/food/dto/CreateFoodFromFavoriteFoodDto.java
  src/main/java/com/diareat/diareat/food/service/FoodService.java
  src/test/java/com/diareat/diareat/controller/FoodControllerTest.java
  src/test/java/com/diareat/diareat/service/FoodServiceTest.java
Labels: feat

#99 Fix: user 패키지 ResponseDto에 기본생성자 추가 (#98)
  src/main/java/com/diareat/diareat/user/dto/response/ResponseRankUserDto.java
  src/main/java/com/diareat/diareat/user/dto/response/ResponseSearchUserDto.java
  src/main/java/com/diareat/diareat/user/dto/response/ResponseSimpleUserDto.java
  src/main/java/com/diareat/diareat/user/dto/response/ResponseUserDto.java
  src/main/java/com/diareat/diareat/user/dto/response/ResponseUserNutritionDto.java
Labels: fix

#100 Fix: user 패키지 ResponseDto에 Serialize 어노테이션 추가 (#98)
  src/main/java/com/diareat/diareat/user/dto/response/ResponseRankUserDto.java
  src/main/java/com/diareat/diareat/user/dto/response/ResponseSearchUserDto.java
  src/main/java/com/diareat/diareat/user/dto/response/ResponseSimpleUserDto.java
  src/main/java/com/diareat/diareat/user/dto/response/ResponseUserDto.java
  src/main/java/com/diareat/diareat/user/dto/response/ResponseUserNutritionDto.java
Labels: fix

#101 Fix: Service 계층 캐싱 중단 (#98)
  src/main/java/com/diareat/diareat/food/service/FoodService.java
  src/main/java/com/diareat/diareat/user/service/UserService.java
Labels: fix

#103 Fix: 서버에서의 시간 의존성 제거
  src/main/java/com/diareat/diareat/food/controller/FoodController.java
  src/main/java/com/diareat/diareat/food/repository/FoodRepository.java
  src/main/java/com/diareat/diareat/food/service/FoodService.java
  src/test/java/com/diareat/diareat/controller/FoodControllerTest.java
  src/test/java/com/diareat/diareat/service/FoodServiceTest.java
Labels: fix

#105 Fix: 유저 검색 API GET -> POST로 수정 (#104)
  src/main/java/com/diareat/diareat/user/controller/UserController.java
  src/test/java/com/diareat/diareat/controller/UserControllerTest.java
Labels: fix

#107 Fix: 서비스 주요 시점 로그 추가 및 팔로우 관련 버그 수정 (#106)
  src/main/java/com/diareat/diareat/user/repository/FollowRepository.java
  src/main/java/com/diareat/diareat/user/service/UserService.java
  src/test/java/com/diareat/diareat/service/UserServiceTest.java
Labels: fix

#109 hotfix: userid반환이 아닌 favorite food id로 제대로 반환하도록 수정 (#108)
  src/main/java/com/diareat/diareat/food/service/FoodService.java
Labels: fix

#111 Fix: timezone 설정 (#110)
  src/main/java/com/diareat/diareat/DiareatApplication.java
Labels: fix

#113 Fix: JPA에게 날짜 정렬 위임 (#112)
  src/main/java/com/diareat/diareat/food/service/FoodService.java
Labels: fix

#115 Fix: 즐겨찾기 버그 수정을 위한 음식-즐겨찾는음식 연관관계 개편 (#114)
  src/main/java/com/diareat/diareat/food/domain/FavoriteFood.java
  src/main/java/com/diareat/diareat/food/domain/Food.java
  src/main/java/com/diareat/diareat/food/repository/FavoriteFoodRepository.java
  src/main/java/com/diareat/diareat/food/service/FoodService.java
  src/main/java/com/diareat/diareat/user/dto/request/JoinUserDto.java
  src/main/java/com/diareat/diareat/user/dto/request/UpdateUserDto.java
  src/main/java/com/diareat/diareat/user/dto/request/UpdateUserNutritionDto.java
Labels: fix

#117 chore: sonarqube workflow 도입 (#116)
  .github/workflows/Diareat-CICD.yml
Labels: chore

#118 chore: 오류로 인한 sonarqube 취소 (#116)
  .github/workflows/Diareat-CICD.yml
Labels: fix

#119 Fix: 즐찾 해제 시 자식 음식객체 연쇄삭제 명시적으로 추가 (#114)
  src/main/java/com/diareat/diareat/food/service/FoodService.java
  src/test/java/com/diareat/diareat/service/FoodServiceTest.java
Labels: fix

#121 Feat: 일별 음식에서 해당 날짜 없으면 0 반환 및 한 주 단위로 묶어 데이터 반환 (#120)
  src/main/java/com/diareat/diareat/food/dto/ResponseAnalysisDto.java
  src/main/java/com/diareat/diareat/food/service/FoodService.java
  src/test/java/com/diareat/diareat/controller/FoodControllerTest.java
  src/test/java/com/diareat/diareat/service/FoodServiceTest.java
Labels: feat

#123 Fix: 기준섭취량 자동계산 boolean 누락된 버그 수정 (#122)
  src/main/java/com/diareat/diareat/auth/component/JwtTokenProvider.java
  src/main/java/com/diareat/diareat/auth/service/CustomUserDetailService.java
  src/main/java/com/diareat/diareat/user/domain/User.java
  src/main/java/com/diareat/diareat/user/dto/request/UpdateUserDto.java
  src/main/java/com/diareat/diareat/user/service/UserService.java
  src/main/java/com/diareat/diareat/util/MessageUtil.java
  src/test/java/com/diareat/diareat/controller/UserControllerTest.java
  src/test/java/com/diareat/diareat/service/UserServiceTest.java
Labels: fix

#124 Fix: ResponseFoodDto에 생성시간 누락 반영 (#122)
  src/main/java/com/diareat/diareat/food/dto/ResponseFoodDto.java
  src/main/java/com/diareat/diareat/food/service/FoodService.java
  src/test/java/com/diareat/diareat/controller/FoodControllerTest.java
Labels: fix

#126 Fix: LocalTime 자료형 분해 및 Analysis 수정
  src/main/java/com/diareat/diareat/food/dto/ResponseFoodDto.java
  src/main/java/com/diareat/diareat/food/service/FoodService.java
  src/test/java/com/diareat/diareat/controller/FoodControllerTest.java
  src/test/java/com/diareat/diareat/service/FoodServiceTest.java
Labels: fix

#127 Fix: 기준섭취량 자동계산 옵션 발동되지 않던 버그 수정 (#122)
  src/main/java/com/diareat/diareat/user/domain/User.java
Labels: fix

#128 Fix: 현재 날짜까지 포함하도록 수정 (#125)
  src/main/java/com/diareat/diareat/food/service/FoodService.java
  src/test/java/com/diareat/diareat/service/FoodServiceTest.java
Labels: fix
