Repository CAUSOLDOUTMEN/Diareat_backend, pull requests merged in 2024-01, with the labels that each got.

#141 Refactor: EntityListener 적용 및 Food Domain 리팩토링
  src/main/java/com/diareat/diareat/DiareatApplication.java
  src/main/java/com/diareat/diareat/config/JpaAuditingConfig.java
  src/main/java/com/diareat/diareat/food/domain/FavoriteFood.java
  src/main/java/com/diareat/diareat/food/domain/Food.java
  src/main/java/com/diareat/diareat/food/dto/ResponseAnalysisDto.java
  src/main/java/com/diareat/diareat/food/dto/ResponseFavoriteFoodDto.java
  src/main/java/com/diareat/diareat/food/dto/ResponseFoodDto.java
  src/main/java/com/diareat/diareat/food/dto/ResponseFoodRankDto.java
  src/main/java/com/diareat/diareat/food/dto/ResponseNutritionSumByDateDto.java
  src/main/java/com/diareat/diareat/food/dto/ResponseScoreBestWorstDto.java
  src/main/java/com/diareat/diareat/food/dto/ResponseSimpleFoodDto.java
  src/main/java/com/diareat/diareat/food/service/FoodService.java
  src/test/java/com/diareat/diareat/controller/FoodControllerTest.java
  src/test/java/com/diareat/diareat/service/FoodServiceTest.java
Labels: refactor

#143 Refactor: 즐찾음식 관계단절 이슈 등 리팩토링 (#142)
  src/main/java/com/diareat/diareat/food/repository/FoodRepository.java
  src/main/java/com/diareat/diareat/food/service/FoodService.java
  src/main/java/com/diareat/diareat/user/domain/BaseNutrition.java
  src/main/java/com/diareat/diareat/user/domain/User.java
  src/main/java/com/diareat/diareat/user/repository/UserRepository.java
  src/test/java/com/diareat/diareat/service/FoodServiceTest.java
Labels: refactor

#148 fix: ddl 업데이트 (#147)
  src/main/resources/application-db.properties
Labels: fix

#149 Feat: JWT AccessToken & RefreshToken 구현
  src/main/java/com/diareat/diareat/auth/component/JwtAuthFilter.java
  src/main/java/com/diareat/diareat/auth/component/JwtTokenProvider.java
  src/main/java/com/diareat/diareat/auth/controller/AuthController.java
  src/main/java/com/diareat/diareat/auth/dto/ResponseJwtDto.java
  src/main/java/com/diareat/diareat/auth/service/CustomUserDetailService.java
  src/main/java/com/diareat/diareat/user/service/UserService.java
  src/main/java/com/diareat/diareat/util/api/ResponseCode.java
Labels: feat

#151 Fix: 메소드 이름 변경에 의해 테스트 코드 수정
  src/test/java/com/diareat/diareat/controller/FoodControllerTest.java
  src/test/java/com/diareat/diareat/controller/UserControllerTest.java
Labels: fix

#153 Fix: ResponseJwtDto에 userId 추가 (#152)
  src/main/java/com/diareat/diareat/auth/controller/AuthController.java
  src/main/java/com/diareat/diareat/auth/dto/ResponseJwtDto.java
Labels: fix

#154 Fix: Jwt 일부 코드 복구 및 RefreshToken 만료 관련 예외처리 반영 (#152)
  src/main/java/com/diareat/diareat/auth/component/JwtTokenProvider.java
  src/main/java/com/diareat/diareat/auth/controller/AuthController.java
  src/main/java/com/diareat/diareat/util/exception/GlobalExceptionHandler.java
  src/main/java/com/diareat/diareat/util/exception/ValidException.java
Labels: fix

#155 Fix: UserRepository entityGraph 관련 오류 수정 (#152)
  src/main/java/com/diareat/diareat/user/repository/UserRepository.java
Labels: fix

#156 Fix: user객체 roles 지연로딩 삭제(#152)
  src/main/java/com/diareat/diareat/user/domain/User.java
Labels: fix
